name: Validate

on:
  push:
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate PHP syntax
        run: find . -name '*.php' -print0 | xargs -0 -n1 php -l
      - name: Validate JSON syntax
        run: find . -name '*.json' -print0 | xargs -0 -n1 jq empty
